### ISSUE TITLE
badges need to have an expiration date (e.g. x days after minting)

### ISSUE THREAD

**Issue by TimDaub** [otterspace-xyz/otterspace-contracts#45]

**Comment by rahulrumalla** [comment]
The idea behind this was that since badges may express permissions, some of these permissions need to be short lived. For ex, a guest badge to a DAO maybe valid only for 30 days and a season pass badge for another DAO maybe valid for 90 days while some badges' permission may never expire. 

Expired badges should not be burned as users want to still own the badge they earned in their wallet. But it maybe not help them get through "token gated" channels for instance.
